name: Deploy to EC2

on:
  push:
    branches: [master]  # Remove space if not intended

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Deploy to EC2
      uses: appleboy/ssh-action@v0.1.7
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USERNAME }}
        key: ${{ secrets.EC2_SSH_KEY }}
        port: 22
        script: |
          cd ludo_backend

          git pull origin master

          npm install

          npx prisma generate
          npx prisma db push

          pm2 restart backend || pm2 start npm --name "backend" -- start
          pm2 restart prisma-studio || pm2 start "npx prisma studio" --name "prisma-studio"

          pm2 save

          echo "✅ Deployment completed successfully!"
