name: Deploy to EC2

on:
  push:
    branches: [master]  # Remove space if not intended

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Deploy to EC2
      uses: easingthemes/ssh-deploy@v4.1.8
      with:
        SSH_PRIVATE_KEY: ${{ secrets.EC2_SSH_KEY }}
        REMOTE_HOST: ${{ secrets.EC2_HOST }}
        REMOTE_USER: ${{ secrets.EC2_USERNAME }}
        SCRIPT_BEFORE: |
          cd ludo_backend
          git pull origin main
          npm install
          npx prisma generate
          npx prisma db push
          pm2 restart backend || pm2 start npm --name "backend" -- start
          pm2 restart prisma-studio || pm2 start "npx prisma studio" --name "prisma-studio"
          pm2 save
          echo "✅ Deployment completed successfully!"

          pm2 save

          echo "✅ Deployment completed successfully!"
